### ISSUE TITLE
Please make it php5.3.* compatible

### ISSUE THREAD

**Issue by peterdd** [thephpleague/oauth2-client#234]
Composer installs only 0.3 version of this library, because all version after that require php5.4.0 or later.

But that version has problems with lower/uppercase name.

php cli 5.3.3
php web 5.3.28

My workaround is
  
    cp AuthorizationCode.php  Authorizationcode.php

But that is no solution for a new Flyspray release we plan.

**Comment by ramsey** [comment]
One of the League requirements is that the packages be PHP 5.4+. Additionally, the class name is correctly `AuthorizationCode`. Why do you need to make the "C" lowercase?

**Comment by tpavlek** [comment]
The bug he's referring to is one that was around before you took over @ramsey. There was an open bug where it didn't properly uppercase the C in authorization code for the default grant type.

@peterdd since 5.4+ is the minimum for the package now, your only solution is the one you presented, or you can fork the project and make changes to `AbstractProvider`. You want to change the getAccessToken method to include this line

```php
$className = str_replace(' ', '', ucwords(str_replace(['-', '_'], ' ', $grant)));
```

instead of the old, incorrect casing rules.

But those are your only two solutions unless you upgrade PHP.

**Comment by rakeev** [comment]
Why not simply fix classname capitalization and tag as 0.3.1?

**Comment by peterdd** [comment]
The current active devs at https://github.com/Flyspray/flyspray aren't experienced with that composer stuff. php5.2.* and php5.3.* is still wide spread on hostings and we want Flyspray be very easy to install and userfriendly.

This oauth2-client seems so far the only showstopper on php5.2.* or php5.3.* environments, so if you know a solution that we can until the release we plan around end this month we would be very glad.
Maybe some composer.json modification? Well, we just don't know to less about composer.

@rakeev: If that is possible and the composer can handle that automatically that would be great!

**Comment by tpavlek** [comment]
I'm not sure if @ramsey wants to tag, but I went ahead and fixed this over here: https://github.com/tpavlek/oauth2-client.

@peterdd here is how you can fix this for your projects. First, go to the above link, I've already performed the capitalization fix and tagged a 0.3.1 release. In the upper right hand corner, click fork, and create a new fork of that project in your account.

You should now be on https://github.com/peterdd/oauth2-client or something similar.

You can now instruct any applications that use oauth2-client to use *your* fork instead of the official PHP League one. All you have to do is in the `composer.json` of the project requiring PHP 5.3 support add a section:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/peterdd/oauth2-client"
    }
]
```

Now, when you run composer update, it will try to install oauth2-client from that repository instead. That way you can still maintain PHP 5.3 support for your projects, regardless of what this project officially supports.

I hope this helps.

**Comment by peterdd** [comment]
Yeah, best way would be a official 0.3.1 version and composer chooses this version when the user with php <5.4.0 version install Flyspray.

Users with newer php versions should be on the offical channel, maintaining additional an own repository of oath2-client sounds a bit painful.

**Comment by peterdd** [comment]
I tried to make a branch "php5.3 compatible" .

But now this dumps Travis CI: https://travis-ci.org/thephpleague/oauth2-client/builds/53698862

    PHP Fatal error:  Using $this when not in object context in /home/travis/build/thephpleague/oauth2-client/test/src/Provider/AbstractProviderTest.php on line 90

Could someone please dig into this and fix it for working all versions php5.3 to current tested php versions?

**Comment by tpavlek** [comment]
I'm just going to put it out there that you're asking for support for an unsupported version. The entire purpose of not supporting old version of PHP is so that the maintainers of the project don't have to support it. It's rather cyclical.

Ramsey might do that. I wouldn't if I were him. Since you want to use the package in the long-haul with an unsupported version of PHP, maintaining your own fork would likely be the best option for you.

Just my 2 cents. Someone else might chime in and help. Maybe.

**Comment by ramsey** [comment]
As I said earlier, PHP 5.4+ is our minimum version. League packages right now are setting that as their baseline, and we will support PHP 5.4+, but not earlier. Sorry.

As @tpavlek suggested, this is a good case for maintaining your own fork of the project. You may still use your fork with Composer.

**Comment by peterdd** [comment]
:-(
