### ISSUE TITLE
Basic http auth headers are not set in POST  curl request 

### ISSUE THREAD

**Issue by vishalmelmatti** [thephpleague/oauth2-client#254]
Hi,

My API test server is behind basic http auth. I have implemented my custom provider and trying to POST request with Basic http auth headers. The prepared POST request do not pass headers. How these headers can be set ?

**Comment by bajb** [comment]
We also have the same issue, and have had to duplicate the getAccessToken method into our provider.

I believe its due to headers being set to null for GET and POST requests.  Not sure if it was intentional or not.

**Comment by ramsey** [comment]
Looks like it's just been that way since the beginning of the project (at least for the POST line). It looks like you added the `$client->get()` line originally here:

https://github.com/thephpleague/oauth2-client/commit/85d88a449eaf253b64a3803474cbe67e8c68b577#diff-58d25fe37b0dacc76bd6b7373506e480R182

:-)

**Comment by ramsey** [comment]
I just tagged release 0.10.1 that provides the fix for this. Thanks, @bajb!

https://github.com/thephpleague/oauth2-client/releases/tag/0.10.1
