### ISSUE TITLE
Calls to IDPException inconsistent?

### ISSUE THREAD

**Issue by jaydiablo** [thephpleague/oauth2-client#256]
Had an issue today where upgrading from 0.6.0 to 0.10.1 was causing google authentication to fail.  This by itself isn't relevant to this ticket (we had to enable the google+ api in our app), but it did get us digging around a bit, as the error message in IDPException wasn't helpful ("Unknown Error").

In AbstractProvider a BadResponseException exception is caught (in the fetchProviderData method), some data manipulation is done, then the IDPException is thrown.  Here's the code for this as of 0.10.1:

```php
        } catch (BadResponseException $e) {
            // @codeCoverageIgnoreStart
            $raw_response = explode("\n", $e->getResponse());
            throw new IDPException(end($raw_response));
            // @codeCoverageIgnoreEnd
        }
```
In this particular case, `$e->getResponse()` returns a Guzzle response object.  When put through the `explode()` call, it ends up like this (xdebug enhanced output):

```
array (size=29)
  0 => string 'HTTP/1.1 403 Forbidden' (length=23)
  1 => string 'Vary: X-Origin, Origin,Accept-Encoding' (length=39)
  2 => string 'Content-Type: application/json; charset=UTF-8' (length=46)
  3 => string 'Date: Fri, 03 Apr 2015 17:59:09 GMT' (length=36)
  4 => string 'Expires: Fri, 03 Apr 2015 17:59:09 GMT' (length=39)
  5 => string 'Cache-Control: private, max-age=0' (length=34)
  6 => string 'X-Content-Type-Options: nosniff' (length=32)
  7 => string 'X-Frame-Options: SAMEORIGIN' (length=28)
  8 => string 'X-XSS-Protection: 1; mode=block' (length=32)
  9 => string 'Server: GSE' (length=12)
  10 => string 'Alternate-Protocol: 443:quic,p=0.5' (length=35)
  11 => string 'Accept-Ranges: none' (length=20)
  12 => string 'Transfer-Encoding: chunked' (length=27)
  13 => string '' (length=1)
  14 => string '{' (length=1)
  15 => string ' "error": {' (length=11)
  16 => string '  "errors": [' (length=13)
  17 => string '   {' (length=4)
  18 => string '    "domain": "usageLimits",' (length=28)
  19 => string '    "reason": "accessNotConfigured",' (length=36)
  20 => string '    "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",' (length=166)
  21 => string '    "extendedHelp": "https://console.developers.google.com"' (length=59)
  22 => string '   }' (length=4)
  23 => string '  ],' (length=4)
  24 => string '  "code": 403,' (length=14)
  25 => string '  "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."' (length=163)
  26 => string ' }' (length=2)
  27 => string '}' (length=1)
  28 => string '' (length=0)
```

Which is the full response (including headers) converted to string form, then exploded on new line.  There is some useful information in this response, if the body is parsed and JSON decoded.  However, in the IDPException throw above, `end()` is used, which just returns the last element of this array, which is an empty string in this case.  IDPException is expecting an array with "code" and "message" keys, otherwise it just sets the exception message to "Unknown Error" which is what it is doing in this case.

Obviously, extracting the code/message keys from that JSON would be ideal here.  I'm not clear on why the response is being exploded by new line and then just the last item being retrieved to be passed as the exception message. I also don't know all possible return values of `$e->getResponse()` here, since I'm just looking at an isolated case, but since it's coming from Guzzle, it seems that it's safe to assume this is always going to be a Guzzle HTTP Response object?

Elsewhere in the AbstractProvider class IDPException is thrown, but appears to follow the expected use case (passing an array):

```php
        if (isset($result['error']) && ! empty($result['error'])) {
            // @codeCoverageIgnoreStart
            throw new IDPException($result);
            // @codeCoverageIgnoreEnd
        }
```

**Comment by ramsey** [comment]
Thanks for the well-researched issue, and sorry it's taken me a while to get back to it.

I can't answer why we're currently grabbing the last element with `end()` and passing that into IDPException. That does look wrong.

It looks like IDPException is looking for three keys in the `$result` array passed to it, and it can also accept a non-array, which, as you've pointed out, results in an "Unknown error." The three keys are:

* code
* error
* message

If `error` is set and is not an empty string, then it becomes the exception message. Otherwise, if `message` is set and not an empty string, then it becomes the exception message.

That logic is where it gets tricky in the case of the Guzzle response. Unless Guzzle provides us access to the raw response body (and not as an array like you show above), then we'll need to piece together the array (indexes 14-27, in your example) and `json_decode()` it. At that point, the `code` and `message` values are sub-properties of the `error` property, which also contains an `errors` property that is an array of errors. I guess all we're really concerned with is are the `code` and `message` properties, so we could pass `$response['error']` to IDPException safely.

However, this does not look like [a proper OAuth2 auth token error response](http://tools.ietf.org/html/rfc6749#section-5.2), and I'm having difficulty finding why we're looking for `code` and `message` properties in the IDPException, when there are clear error properties outlined in the OAuth2 spec. Is this because most providers don't follow the spec?

If that's the case, then we need to rethink how IDPException works and pass more control down to the individual providers. We are already splitting the providers off into separate repositories (see the Google one here: https://github.com/thephpleague/oauth2-google).

@alexbilbie, any thoughts on why these decisions were made? Anything I should beware of when changing this? Thanks!

**Comment by vimishor** [comment]
> I can't answer why we're currently grabbing the last element with end() and passing that into IDPException. That does look wrong.

Related to 57fbc1d43311430d69fd9cf187f64105caacc73e. @TomHAnderson

**Comment by ramsey** [comment]
Actually, it looks more like it's related to https://github.com/thephpleague/oauth2-client/commit/aa58cd48cdb59fc343abc8907dbcb7380528acda. Tom's commit just moved it to a different location.

**Comment by vimishor** [comment]
Yes, you are right. It looks like I lack the search-fu today :)

**Comment by alexbilbie** [comment]
@ramsey sorry Ben, I wrote this so long ago I can't remember, it might even be a legacy from Phil's original CodeIgniter library...

**Comment by ramsey** [comment]
@jaydiablo, going to address this in v1.0. Thanks!

**Comment by jaydiablo** [comment]
Good to hear!  Thanks!

**Comment by ramsey** [comment]
I believe our recent changes to IDPException (see #269) have taken care of this. Let me know if you think it's still inconsistent. The idea now is to let providers parse things before passing them into the exception. You may also want to check out the discussion on #263 for background on how we got to #269. :-)
