### ISSUE TITLE
Normalize meta?

### ISSUE THREAD

**Issue by pierrejoye** [thephpleague/oauth2-client#259]
hi,

Thanks for taking over this great component :)

not sure it is by design or a bug, but it seems the Entity User does not match with the github provider result, forcing to extend it:

https://github.com/jubianchi/pickleweb/blob/master/src/Auth/GithubProvider.php#L9

it would be handier to have the mapping in the provider response handler instead. Or?

**Comment by kevindierkx** [comment]
Working on a somewhat different solution in #237

**Comment by ramsey** [comment]
@pierrejoye See also #265, which I think will resolve this.

**Comment by ramsey** [comment]
After lots of discussion in #265 and a PR in #267, we've removed the User entity and have replaced it with a `Provider\UserInterface`. Third-party providers should use this and handle user data however they need (since user data is always specific to the provider and not to OAuth 2.0). However, to help make things easier, we are working on a way to use Providers to make authenticated requests using the OAuth tokens against the provider's API (see #268).
