### ISSUE TITLE
Support for PHP 5.3.10

### ISSUE THREAD

**Issue by jagandecapri** [thephpleague/oauth2-client#391]
This might be an unrelated question to this repo.

I can't upgrade my client's PHP version which is PHP 5.3.10. 

Since this library only supports 5.5 and above, is there any workaround or other libraries to support 5.3.10?

**Comment by ramsey** [comment]
Unfortunately, there are no easy work-arounds, since the library uses constructs that are only available in PHP 5.5+. The earliest version of the library that supports 5.3 is version 0.3.0, and I wouldn't recommend going that far back.

There are other OAuth libraries you may be able to use, but since PHP 5.3 reached its end of life on 14 August 2014, many libraries will no longer support it in their newer versions. I'd recommend searching around Packagist and oauth.net.

**Comment by jagandecapri** [comment]
Thanks @ramsey
