### ISSUE TITLE
Request or QueryString Parameters Pass

### ISSUE THREAD

**Issue by muhammedfatih** [thephpleague/oauth2-client#414]
I try to use this library for my own Rest Service with OAuth 2.0 security. Even though I perfectly use it to get authentication tokens or refreshing them or getting service response without any parameter necessity, I can not make any request for service with parameters. 

My request test page code is 
```

<?php

include("configs.php"); // My database connections are here, also $ClientSecret, $ClientId and $RedirectUri are here. 
require_once __DIR__.'/vendor/autoload.php';

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
	'clientId'                => $ClientId,       // The client ID assigned to you by the provider
	'clientSecret'            => $ClientSecret,   // The client password assigned to you by the provider
	'redirectUri'             => $RedirectUri,    //Your redirectUri
	'urlAuthorize'            => 'http://api.xxx.com/authorize.php',
	'urlAccessToken'          => 'http://api.xxx.com/token.php',
	'urlResourceOwnerDetails' => 'http://api.xxx.com/resource.php',
]);

$request=$provider->getAuthenticatedRequest("GET", "http://xxx/api-server/v1/orders/list/", "2a662d337a8eabcea36d7c361c570c1f42bf9bf3");
print_r($provider->getResponse($request));

?>
```  

Can anybody help me how to request a service with parameter?

**Comment by stevenmaguire** [comment]
If your service is using Authorization headers it appears as if your token may not actually be included in the authenticated request. This is likely a problem with the design of the generic provider, rather than the client project itself. The `getAuthorizationHeaders ` currently returns an empty array regardless of the token provided. When building a specific provider, this method is often implemented in the child class for specific behavior. 

I haven't actually run this code, and am only looking through the project. So with that in mind, my advice would be to configure the options, including authorization header, before creating the authenticated request and pass into the method using the fourth parameter. 

```php
$options = [
    'headers' => [
        "Authorization" => "Bearer 2a662d337a8eabcea36d7c361c570c1f42bf9bf3"
    ],
];
$request=$provider->getAuthenticatedRequest("GET", "http://xxx/api-server/v1/orders/list/", "", $options);
```

Trace: 
1) https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L566
2) https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L580
3) https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L809
4) https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L796

**Comment by shadowhand** [comment]
@stevenmaguire that doesn't quite make sense because the [authorization headers are added](https://github.com/thephpleague/oauth2-client/blob/cd64ef49e6b44660fed5c25efb2b22556deb787d/src/Tool/BearerAuthorizationTrait.php#L30-L33) via the [`BearerAuthorizationTrait`](https://github.com/thephpleague/oauth2-client/blob/cd64ef49e6b44660fed5c25efb2b22556deb787d/src/Provider/GenericProvider.php#L29).

**Comment by muhammedfatih** [comment]
No luck, It does not work any way. If you trace you can see Guzzle Requeset Options does not work for this repo. 

First of all, [Guzzle does not have any query options](https://github.com/thephpleague/oauth2-client/blob/1b0fe447ae474bcfd83f3f8578ce45f5077f2630/src/Tool/RequestFactory.php), it is "body" most high probability. 

Secondly even if you make **query**, **body** it does not work again, because it does not accept array, but only *string*. 

Thirdly, my problem still continuing.

**Comment by shadowhand** [comment]
It would help us debug if you showed specifically what is not working. What exactly do you mean by "parameters"?

**Comment by muhammedfatih** [comment]
Parameters I meant area QueryString and Request Values, the values that I can send with POST and GET methods.

In this case, for instance I want to filter my order list (the service I call above) according to some queryString values such as costumerName. How to pass this queryString value?

**Comment by shadowhand** [comment]
You should be able to put them right in the URL:

```
$request=$provider->getAuthenticatedRequest('GET', 'http://xxx/api-server/v1/orders/list/?product=15&limit=10', $token);
```

**Comment by muhammedfatih** [comment]
How to post parameters? This only allow me sending queryStrings(via GET Method) not POSTing parameters. I also need POST Method.  

How to pass POST parameters via ```$provider-> getAuthenticatedRequest('POST', $url, $token);``` way?

I want to send product and limit parameters via POST.

**Comment by shadowhand** [comment]
@muhammedfatih to use form data:

```php
$options['body'] = http_build_query($parameters);
$request = $provider->getAuthenticatedRequest('POST', $url, $token, $options);
```

Or to post a JSON body:

```php
$options['body'] = json_encode($parameters);
````

**Comment by muhammedfatih** [comment]
Excellent. Thank you so much, it works :)

**Comment by muhammedfatih** [comment]
Is parameters an array? If so, It does not work :/

**Comment by muhammedfatih** [comment]
Is parameters an array? If so, It does not work :/

**Comment by shadowhand** [comment]
Whatever you pass into `$options['body']` must be a string encoded for whatever `Content-Type` you are sending. You could also do this:

```php
$request = $provider->getAuthenticatedRequest('POST', $url, $token);
$request = $request->withHeader('Content-Type', 'application/json');
$request->getBody()->write(json_encode($stuff_to_send));

**Comment by muhammedfatih** [comment]
Perfect! It works, thank you @shadowhand !

A notice for people who have the same problem, I use content-type as ```application/x-www-form-urlencoded```. I can POST something with the code above. To GET something I added my parameters end of the endpoint. Examples:

```
$request=$provider->getAuthenticatedRequest("GET", "http://xxx/v1/orders/list/?costumerName=fatih", "2a662d337a8eabcea36d7c361c570c1f42bf9bf3");
print_r($provider->getResponse($request));
```

```
$request=$provider->getAuthenticatedRequest("POST", "http://xxx/v1/orders/accept/", "2a662d337a8eabcea36d7c361c570c1f42bf9bf3");
$request = $request->withHeader('Content-Type', 'application/x-www-form-urlencoded');
$request->getBody()->write(http_build_query(array("orderItemId"=>"asd")));
print_r($provider->getResponse($request));
```

**Comment by peteclark3** [comment]
Thank u @muhammedfatih
