### ISSUE TITLE
PrepareAccessTokenResponse must be of the type array error

### ISSUE THREAD

**Issue by mandado** [thephpleague/oauth2-client#466]
I trying authenticate with oauth2-client, and give this error 
```
 Catchable fatal error: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given, called in C:\wamp\www\stackexchange\vendor\league\oauth2-client\src\Provider\AbstractProvider.php on line 540 and defined in C:\wamp\www\stackexchange\vendor\league\oauth2-client\src\Provider\AbstractProvider.php on line 711
````

The code that i used is same of first example in this repository.
Is a bug ? how i can to solve this ?

**Comment by rtheunissen** [comment]
This is because [`parseResponse`](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L668) can return a `string` or `array` (even though the return typehint is `array`), but [`prepareAccessTokenResponse`](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L711) requires an `array`.

This is something that I addressed in #408, because it should be fine for `parseResponse` to return a string, and for `prepareAccessTokenResponse` to receive it. It's possible (even if not according to the spec), for the response to be neither of urlencoded or json, in which case the best we can do is return the string and delegate the parsing to the extending provider. 

It's not this library's responsibility to enforce the OAuth2 spec. If we can't parse the result, then forwarding the body string should be okay. The provider can decide what it does with it.

So to fix this, it would require a typehint update, which breaks BC, right?

---

First things first, @mandado what provider are you using? It's unexpected (but possible) for the parsed access token response to be a string.

**Comment by mandado** [comment]
@rtheunissen  i use GenericProvider.

**Comment by rtheunissen** [comment]
@mandado and the service? StackOverflow (guess based on your project dir)?

If you `var_dump` the value of `$response` [here](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L539), what do you see? 

Would need to edit the file in /vendor.

**Comment by mandado** [comment]
yes, i'm trying authenticate with stackoverflow.

```var_dump``` the value ``` $response``` this return ```access_token=mytokenhere&expires=86199```

**Comment by rtheunissen** [comment]
Could you also check the value of `$type` [here](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L671)? As a bonus, would be good to see all the headers returned. I think you can use `$response->getHeaders()`.

**Comment by mandado** [comment]
value ``` $type ``` is 'text/plain; charset=utf-8' 

value ``` $response->getHeaders()``` is array of headers from request.

**Comment by rtheunissen** [comment]
Looks like SE is not setting the correct response headers.

**Comment by mandado** [comment]
what is SE ? @rtheunissen

**Comment by rtheunissen** [comment]
Stack Exchange. :) 

If they set the correct headers, the provider would parse the string and use the array as expected.

I sent them a tweet as it should be fixed anyway. The question is how we should handle cases where an access token response body can't be parsed (either due to bad headers or an unexpected encoding).

**Comment by mandado** [comment]
@rtheunissen i saw in documentation about authentication and says nothing about headers :/

**Comment by rtheunissen** [comment]
@mandado it's something that they are not doing right; nothing you are doing wrong.

**Comment by mandado** [comment]
@rtheunissen  ahh yes hehehe. how should I proceed ? wait for an answer about this error in this issue ?

**Comment by rtheunissen** [comment]
Yeah would need to wait for @ramsey and @shadowhand to decide how we handle cases like these.
For now I'd recommend either forking temporarily or using a temporary edited AbstractProvider.php in your /vendor. 

[This conditional](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L673) should pass if their headers were set correctly, so adjust that. You could also just drop the conditional entirely (as well as all the JSON stuff that follows).

Keep in mind that this is **not a good solution**. It's just temporary so you can get on with developing.

**Comment by mandado** [comment]
@rtheunissen understand, thanks very much for support :) :+1:

**Comment by nspyke** [comment]
This is still an issue.

This is an intermittent issue, but usually happens after a session timeout.
In this case, I left my browser open overnight, reloaded the page in the morning, and then received this exception.
If I reload the page again after the exception, everything works as expected.

I'm using Silex, running on PHP 5.6.15, Ubuntu 14.04, Nginx, PHP-FPM.

Stack trace
```
Catchable fatal error: Argument 1 passed to League\OAuth2\Client\Provider\GenericProvider::createResourceOwner() must be of the type array, string given, 
called in /vagrant/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 763 and defined in 
/vagrant/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 223
Call Stack
#	Time	Memory	Function	Location
1	0.0001	235784	{main}( )	.../index.php:0
2	0.0250	705536	Silex\Application->run( )	.../index.php:17
3	0.0266	789264	Silex\Application->handle( )	.../Application.php:477
4	0.0383	1002728	Symfony\Component\HttpKernel\HttpKernel->handle( )	.../Application.php:496
5	0.0383	1003584	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	.../HttpKernel.php:62
6	0.0508	1212728	call_user_func_array:{/vagrant/vendor/symfony/http-kernel/HttpKernel.php:139} ( )	.../HttpKernel.php:139
7	0.0508	1212928	Workshop\Controller\DefaultController->indexAction( )	.../HttpKernel.php:139
8	0.0508	1213056	Workshop\Controller\DefaultController->render( )	.../DefaultController.php:41
9	0.0548	1227072	Pimple\Container->offsetGet( )	.../DefaultController.php:125
10	0.0548	1227152	Workshop\Application->Workshop\{closure}( )	.../Container.php:113
11	0.0648	1405024	League\OAuth2\Client\Provider\AbstractProvider->getResourceOwner( )	.../Application.php:197
12	1.5436	1678688	League\OAuth2\Client\Provider\GenericProvider->createResourceOwner( )	.../AbstractProvider.php:763
```
Stack trace screenshot: https://www.dropbox.com/s/4hocj5m21tsxuut/Screenshot%202016-01-14%2010.18.32.png?dl=0&preview=Screenshot+2016-01-14+10.18.32.png

I'm thinking if we cast the response to an array, it should fix this exception. 
I need to investigate more to confirm.

\League\OAuth2\Client\Provider\AbstractProvider::getResourceOwner:761
```
$response = (array) $this->fetchResourceOwnerDetails($token);
```

**Comment by ramsey** [comment]
Sorry, just now reading through this thread…

The GenericProvider only works for providers that don't deviate from the OAuth2 specification. If a provider deviates, you'll need to extend AbstractProvider and create your own provider. Take a look at the [provider guide](https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDER-GUIDE.md) for how to do this.

Additionally, maybe a fatal error isn't the best approach for this. Maybe instead of type-hinting the array, we should accept anything and then do the check inside the method and throw a more friendly exception? 

Thoughts, @shadowhand?

**Comment by shadowhand** [comment]
There's really nothing we can do about SE not providing the correct headers. We might want to throw an exception if no acceptable parsing method is found, instead of just returning the response directly. This would avoid that fatal and place the burden on the server and developer. At least a try/catch can be used to trap the problem.

**Comment by ramsey** [comment]
I think the correct solution here is to create your own provider extending from AbstractProvider, since our GenericProvider can't handle Stack Exchange's non-conforming behavior. You might consider providing your custom Stack Exchange provider as an open source library, and we can link to it from our README.PROVIDERS.md when it is ready.

**Comment by imranmunawar** [comment]
I am getting this error at $response = $this->getResponse($request), Please help me on this.
<!DOCTYPE html>\n
<html>\n
    <head>\n
        <meta charset="UTF-8" />\n
        <title>An Error Occurred: Not Acceptable</title>\n
    </head>\n
    <body>\n
        <h1>Oops! An Error Occurred</h1>\n
        <h2>The server returned a "406 Not Acceptable".</h2>\n
\n
        <div>\n
            Something is broken. Please let us know what you were doing when this error occurred.\n
            We will fix it as soon as possible. Sorry for any inconvenience caused.\n
        </div>\n
    </body>\n
</html>\n

**Comment by ramsey** [comment]
@imranmunawar, please open a new issue and provide some of the code you are using, in addition to the service you are attempting to get a response for. Thanks!
