### ISSUE TITLE
Get headers from response

### ISSUE THREAD

**Issue by djchen** [thephpleague/oauth2-client#522]
Is there a way for an end user of this library to get the response headers from an authenticated request?

ie. in this simple example
```
        $request = $provider->getAuthenticatedRequest(
            'GET',
            'http://brentertainment.com/oauth2/lockdin/resource',
            $accessToken
        );
        $response = $provider->getResponse($request);
```

Could we access the headers from the response?

**Comment by ramsey** [comment]
The authenticated request object that is returned is an instance of `Psr\Http\Message\RequestInterface`, so it may be used with any PSR-7 compliant HTTP client. In the case of your example, you're using the default `getResponse()` method, which will parse the response and give you back an array representation of the body. However, we can easily use an HTTP client to create the response ourselves so that we can see the headers, etc.

For example:

``` php
$request = $provider->getAuthenticatedRequest(
    'GET',
    'http://brentertainment.com/oauth2/lockdin/resource',
    $accessToken
);

$client = new \GuzzleHttp\Client();
$response = $client->send($request);
$rawBody = $response->getBody()->getContents();
```

Now you have a real `$response` object that you may use to access headers, status codes, etc.. See Guzzle's documentation on "[Using Responses](http://docs.guzzlephp.org/en/latest/quickstart.html#using-responses)" for more details and examples.

Of course, you don't have to use [Guzzle](https://github.com/guzzle/guzzle). You may use any PSR-7 compliant HTTP client.

**Comment by shadowhand** [comment]
It's actually even easier than what @ramsey listed, you can re-use the client that is provided (which is also currently Guzzle):

```php
$response = $provider->getClient()->send($request);
```

**Comment by ramsey** [comment]
Ah, yes. For some reason, I thought `getHttpClient()` was protected.
