### ISSUE TITLE
```redirect_uri``` can only be set during instantiation of the OAuth Provider?

### ISSUE THREAD

**Issue by holtkamp** [thephpleague/oauth2-client#612]
It seems one **has** to provide the ```redirect_uri``` as part of the ```$options``` array when instantiating a OAuth2Provider. 

I would like to have a DependencyInjectionContainer instantiate the OAuth2Provider using *only* the ```clientId``` and ```clientSecret``` parameters, and then have our application logic figure out the ```redirect_url``` and hand it over in one of these approaches:

- ```$provider->authorize(['redirect_uri' => 'run-time assembled URLgoes here']);```
- ```$authorizationUrl = $provider->getAuthorizationUrl(['redirect_uri' => 'run-time assembled URLgoes here']);```

This is currently not possible. However, our DIC should not be aware of any redirectUrls... Is this limitation on purpose?

**Comment by stevenmaguire** [comment]
Can I ask which service you are planning to consume with this expected functionality? There are no absolutes in the OAuth conversation and many API providers require an explicit list of acceptable `redirect_uri`s be configured within their application's developer portals as an additional security measure. This security measure, when present, would directly compete with your desire to generate URLs on-demand. My guess is that many iterations ago it was decided to not implement the setter method in question because it likely not be useful due to the redirect uri whitelisting.

If you are consuming a very specific API that does not implement this whitelisting requirement, may I suggest building a custom client, if it doesn't already exist, or extending an existing client to add the setter method in question?

**Comment by holtkamp** [comment]
>and many API providers require an explicit list of acceptable redirect_uris be configured within their application's developer portals as an additional security measure.

Yeah, this was also the case, had to register specific URLs. So I now have stored this URL as (DTAP environment-specific) setting instead of autogenerating it. 

I think you are right, I should have reported back here and closed the issue to prevent others from wasting energy on this, sorry! => closing issue.
