### ISSUE TITLE
composer install error 

### ISSUE THREAD

**Issue by sinamorawej** [thephpleague/oauth2-client#637]
Hi
i'm getting the following error when running composer:
`php composer.phar require league/oauth2-client`:

```
Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - The requested package league/oauth2-client No version set (parsed as 1.0.0) is satisfiable by league/oauth2-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
```

any help appreciated

thanks,
sina

**Comment by ramsey** [comment]
If you're able, can you paste the contents of your `composer.json` file here? Please do not include any personal or sensitive information when you paste it.

Also, what version of PHP are you using, and is your `composer.phar` the latest version of Composer?

**Comment by sinamorawej** [comment]
Thanks for the reply.
I've never used composer before and installed the latest version this morning. This also explains my wrong approach to get it working. I managed to resolved it by using: php composer.phar install under /oauth2-client-master
 
My php version: 
PHP 5.6.30 (cli) (built: May  6 2017 09:35:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

Although I tried various entries under require in composer.json, when finally got it working I was using the original.

Here is what I got under vendor:
rwxr-xr-x   xxx   170B 30 Jun 10:41 guzzlehttp
drwxr-xr-x   xxx   102B 30 Jun 10:41 paragonie
drwxr-xr-x   xxx   170B 30 Jun 10:41 eloquent
drwxr-xr-x   xxx   102B 30 Jun 10:41 jakub-onderka
drwxr-xr-x  xxx   408B 30 Jun 10:42 sebastian
drwxr-xr-x   xxx   102B 30 Jun 10:42 webmozart
drwxr-xr-x   xxx   170B 30 Jun 10:42 phpdocumentor
drwxr-xr-x   xxx   102B 30 Jun 10:42 phpspec
drwxr-xr-x   xxx   102B 30 Jun 10:42 myclabs
drwxr-xr-x   xxx   306B 30 Jun 10:42 phpunit
drwxr-xr-x   xxx   102B 30 Jun 10:42 squizlabs
drwxr-xr-x   xxx   204B 30 Jun 10:42 bin
drwxr-xr-x   xxx   238B 30 Jun 11:37 psr
drwxr-xr-x   xxx   136B 30 Jun 11:37 doctrine
drwxr-xr-x  xxx  578B 30 Jun 11:37 symfony
drwxr-xr-x   xxx   102B 30 Jun 11:38 knpuniversity
drwxr-xr-x  xxx   374B 30 Jun 11:38 composer
-rw-r--r--   xxx   178B 30 Jun 11:43 autoload.php
thanks,
Sina

**Comment by ramsey** [comment]
It looks like you've downloaded the oauth2-client source code, but if you're trying to use this library in a project you're building, there's no need to download it. You can use Composer to require it as a dependency for your project.

I think you should take a look at a few Composer tutorials to get a good understanding of the purpose of Composer and how it works. Here are a few that I've found helpful:

* https://www.youtube.com/watch?v=d_zPOJ8cz_A
* https://www.frobiovox.com/posts/2016/08/16/basic-hello-world-with-composer-and-php.html
* https://www.sitepoint.com/re-introducing-composer/
* https://nomadphp.com/composer-the-right-way/

Once you've grasped the concepts of Composer (it's not hard, but it's a bit different if you're not used to dependency management, like with `npm`, `pip`, or `gem`), then you can require `league/oauth2-client` as a project dependency simply by typing from your project root:

```
composer require league/oauth2-client
```

That will handle download this library into your vendor folder so that you can use it in your project.

But first, go check out some of those tutorials. Good luck!

**Comment by sinamorawej** [comment]
Very useful - thanks for your help.
