### ISSUE TITLE
Using GenericProvider

### ISSUE THREAD

**Issue by dennisgeerts** [thephpleague/oauth2-client#678]
I want to implement an API that is not in the 3rd party list (created by my city).

My code in the controller looks like this:

```
public function profielLogin() {
    $provider = new \League\OAuth2\Client\Provider\GenericProvider([
        'clientId'                => 'xxxx',
        'clientSecret'            => 'xxxx',
        'redirectUri'             => 'http://localhost/codeigniter/login/city/profielCallback',
        'lng'                     => 'nl',
        'scope'                   => 'username+name+avatar+email+phone',
        'service'                 => 'stad-profiel-v1',
        'response_type'           => 'code',
        'urlAuthorize'            => 'https://api-oauth2-o.city.be/v1/authorize',
        'urlAccessToken'          => 'https://api-gw-o.city.be/stad/profiel/v1/oauth2/token',
        'urlResourceOwnerDetails' => 'https://api-gw-o.city.be/stad/profiel/v1/v1/me'
    ]);

    echo '<pre>';
    var_dump( $provider );
    echo '</pre>';
}

public function profielCallback() {
    var_dump($_POST);
    var_dump($_GET);
}
```

Using my browser and navigating to the profielLogin() function just returns "service not valid". 

When I browse to the following URL: 
[https://api-oauth2-o.city.be/v1/authorize?client_id=xxxx&redirect_uri=http://localhost/codeigniter/login/city/profielCallback&lng=nl&scope=username+name+avatar+email+phone&service=stad-profiel-v1&response_type=code](url)

I will get redirected to my redirect URI with a query parameter "code" containing my authorization code! 

What am I doing wrong?

**Comment by ramsey** [comment]
I'm not sure where the "service not valid" message is coming from, but in your `profielLogin()` method, you need to redirect the user to the authorization URL. Depending on your framework of choice, the redirection method may be different, but it could look something like this:

``` php
header('Location: ' . $provider->getAuthorizationUrl());
```

You should probably also instantiate your provider somewhere else (maybe in your constructor or in a service locator object?), so that you can reuse it in the `profielCallback()` method, where you'll want to do something like this:

``` php
$accessToken = $provider->getAccessToken('authorization_code', [
    'code' => $_GET['code']
]);
```

Check out the full example in `README.md` and let us know if this doesn't work.
