### ISSUE TITLE
brand new to oauth2, basic questions

### ISSUE THREAD

**Issue by xraphael75** [thephpleague/oauth2-client#699]
I am trying to connect to the allscripts.com FHIR server with oauth2. I installed the oauth2-client and I've been trying to understand how it works. The allscripts.com documentation near the bottom of the page here:

[]https://developer.allscripts.com/Content/fhir/content/overview/

lists an authorize and token server, but it doesn't list a resource server, which the oauth2-client needs. I'm not sure what to put for that. I tried entering 

`'urlResourceOwnerDetails'` => 'https://tw171.open.allscripts.com/FHIR/Patient',

When the page redirected to my redirect url I got this:

[]http://<redirect_url>?error=invalid_request&state=2a1587af166bc939faa7d3400b7495ef

I'm not sure what that error means or the state code.

Also, I am unclear as to where the code block (starting with if(!isset($_GET['code'])){...) in the example here 

[]https://github.com/thephpleague/oauth2-client

should go. Would it be on every page in the application?

I'm very sorry for such basic questions. Thank you for any help.

**Comment by ramsey** [comment]
> lists an authorize and token server

In short, after looking through their docs, it looks like this is how you need to configure the request, using the `GenericProvider`:

``` php
$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'YOUR_CLIENT_ID',
    'clientSecret'            => 'YOUR_SECRET',
    'redirectUri'             => 'http://example.com/your-redirect-url/',
    'urlAuthorize'            => 'https://tw171.open.allscripts.com/authorization/connect/authorize',
    'urlAccessToken'          => 'https://tw171.open.allscripts.com/authorization/connect/token',
    'urlResourceOwnerDetails' => '???',
    'scopes'                  => ['permissions', 'your', 'app', 'requests'],
]);
```

> but it doesn't list a resource server, which the oauth2-client needs. I'm not sure what to put for that.

I think you're on the right path here, but their server doesn't provide an authenticated "me" (or user/owner) resource like many other services do, so this is going to be tricky.

What you really need is this URL:

    https://tw171.open.allscripts.com/FHIR/Patient/id

Where that "id" on the end is the identifier for the user who has authorized access.

Unfortunately, it doesn't look like you can get to this URL without using `https://tw171.open.allscripts.com/FHIR/Patient` to search for a patient, and even then, I'm not sure how you're able to get the record for the patient that is currently authorized, unless a simple request with no parameters to that search endpoint returns search results that list all patients the currently authorized user can access.

As a result, you may not be able to use the `GenericProvider` for your case, since it requires a `urlResourceOwnerDetails`. However, that's not a problem. The library is meant to be extended, so all you really need to do is write your own class. Something like this should do the trick:

``` php
namespace My\OAuth2;

use League\OAuth2\Client\Provider\AbstractProvider;
use League\OAuth2\Client\Token\AccessToken;
use League\OAuth2\Client\Tool\BearerAuthorizationTrait;
use Psr\Http\Message\ResponseInterface;

class AllscriptsProvider extends AbstractProvider
{
    use BearerAuthorizationTrait;

    /**
     * Get authorization url to begin OAuth flow
     *
     * @return string
     */
    public function getBaseAuthorizationUrl()
    {
        return 'https://tw171.open.allscripts.com/authorization/connect/authorize';
    }

    /**
     * Get access token url to retrieve token
     *
     * @param  array $params
     *
     * @return string
     */
    public function getBaseAccessTokenUrl(array $params)
    {
        return 'https://tw171.open.allscripts.com/authorization/connect/token';
    }

    /**
     * Get provider url to fetch user details
     *
     * @param  AccessToken $token
     *
     * @return string
     */
    public function getResourceOwnerDetailsUrl(AccessToken $token)
    {
        // You don't have one. You might consider throwing an exception here so
        // that, when this is called, you get an error and can code your
        // application to ensure that nothing calls this.
        //
        // Note that $this->getResourceOwner() is the most likely culprit for
        // calling this. Just don't call getResourceOwner() in your code.
    }

    /**
     * Get the default scopes used by this provider.
     *
     * This should not be a complete list of all scopes, but the minimum
     * required for the provider user interface!
     *
     * @return array
     */
    protected function getDefaultScopes()
    {
        return ['permissions', 'your', 'app', 'requests'];
    }

    /**
     * Check a provider response for errors.
     *
     * @throws IdentityProviderException
     * @param  ResponseInterface $response
     * @param  array $data Parsed response data
     * @return void
     */
    protected function checkResponse(ResponseInterface $response, $data)
    {
        // Write code here that checks the response for errors and throws
        // an exception if you find any.
    }

    /**
     * Generate a user object from a successful user details request.
     *
     * @param array $response
     * @param AccessToken $token
     * @return \League\OAuth2\Client\Provider\ResourceOwnerInterface
     */
    protected function createResourceOwner(array $response, AccessToken $token)
    {
        // Leave empty. You can't use this, since you don't have a clear
        // resource owner details URL. You might consider throwing an
        // exception from here, as well. See note on
        // getResourceOwnerDetailsUrl() above.
    }
}
```

Then, all you need to do is:

``` php
$provider = new AllscriptsProvider([
    'clientId'                => 'YOUR_CLIENT_ID',
    'clientSecret'            => 'YOUR_SECRET',
    'redirectUri'             => 'http://example.com/your-redirect-url/',
]);
```

If the scopes you require differ from what you put in the default scopes for the class, you can pass those in here, as well.

> I'm not sure what that error means or the state code.

The error *could* be because you didn't provide any scopes; I'm not certain.

For the state code, before redirecting the user to the authorization URL, you'll want to do something like this:

``` php
$_SESSION['oauth2state'] = $provider->getState();
```

That stores the generated state code to the user's session. Then, when the provider redirects back to your `redirectUri`, you want to check the state code they give you against the one stored in the user's session. If it doesn't match, then that tells you something fishy is going on:

``` php
if (empty($_GET['state']) || (isset($_SESSION['oauth2state']) && $_GET['state'] !== $_SESSION['oauth2state'])) {
    if (isset($_SESSION['oauth2state'])) {
        unset($_SESSION['oauth2state']);
    }

    // Something fishy happened. Ask the user to attempt to authorization again.
}
```

> Also, I am unclear as to where the code block [...] should go

No, it doesn't need to be on every page. This should only be on the page that you define as your `redirectUri`. That's where you'll do these checks and then store the access token somewhere to use later when making Allscripts API requests on other pages.

Hope this helps!

**Comment by xraphael75** [comment]
Thank you so much for this detailed response! I will test it out this week.

**Comment by xraphael75** [comment]
In my test it returned this in the redirect url:

`https://tw171.open.allscripts.com/authorization/connect/authorize?state=f2ca17c6811046d738061f529b9c5fdf&scope=permissions%2Cyour%2Capp%2Crequests&response_type=code&approval_prompt=auto&redirect_uri=<redirect_url>&client_id=<client_id>`

and in my browser:

> Secure Connection Failed
> 
> The connection to the server was reset while the page was loading.
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

I'm not sure if I did something wrong or if the problem is on their side. It seems that their documentation is lacking.

**Comment by horsebuzz** [comment]
I am very new to OAuth2. I am trying to implement [split payments api](http://splitpayments.com.au) into my project.

I have completed first task of Authorisation and in `callback.php` I have saved the `refresh_token` and `expires_at` values in database for the user and `access_token` in session.

I have few question of how should I approach from here.

1) After 2 hours the `access_token` expires so should I store `expires_at` values in session as well or determine if the `access_token` is expired or not based on the response.

2) If I were to determine that based on the response then in case of expired token or Revoked Access I get the same status code = 401. How should I make a request that it determines the response has 401 code and should get the `refresh_token` to get new `access_token` or send user for Authorisation process again.

I am using the same extended class `AllscriptsProvider ` you provided up here.

Thank you

**Comment by JoshuaFlood** [comment]
The documentation is complete.

If you look at the `thephpleague/oauth2-client` github page or view the README.md file, you can see under the 'Providers' heading in the setup instructions that there is [a link](https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDER-GUIDE.md) to an explanation of how to develop a custom provider.

The remainder of this comment is an excerpt from that file...

"The AbstractProvider does not specify an access token resource owner identifier. It is the responsibility of the provider class to set the ACCESS_TOKEN_RESOURCE_OWNER_ID constant to the string value of the key used in the access token response to identify the resource owner.

```
/**
 * @var string Key used in the access token response to identify the resource owner.
 */
const ACCESS_TOKEN_RESOURCE_OWNER_ID = null;
```
Once this is set on your provider, when calling `AbstractProvider::getAccessToken()`, the `AccessToken` returned will have its `$resourceOwnerId` property set, which you may retrieve by calling `AccessToken::getResourceOwnerId()`.

The next step is to implement the `AbstractProvider::createResourceOwner()` method. This method accepts as parameters a response array and an `AccessToken`. You may use this information in order to request resource owner details from your service and construct and return an object that implements `League\OAuth2\Client\Provider\ResourceOwnerInterface`. This object is returned when calling `AbstractProvider::getResourceOwner()`."
