### ISSUE TITLE
[Question] Need for fetching resource owner details?

### ISSUE THREAD

**Issue by mlambley** [thephpleague/oauth2-client#729]
Good day,

As part of extending `AbstractProvider` I need to override the `createResourceOwner` and `getResourceOwnerDetailsUrl` functions. I have just left these with a blank implementation and it hasn't caused a problem so far. My first question is, what will break if I do not implement these properly?

My second question is, what is this resource owner information functionality and why does it exist? Is it part of the OAuth2 specification? I can't find anywhere on the interwebs that describes the purpose of this.

Do you have some documentation, preferably within the OAuth2 specification, which describes the purpose and usefulness for fetching and using resource owner information?

**Comment by ramsey** [comment]
The resource owner functionality is not part of the OAuth 2 specification. It's merely provided for convenience.

If you do not implement these fully, the only functionality that will break is a call to `$provider->getResourceOwner()`. If you don't need this functionality, then I don't think there will be any problems if you choose not to fully implement these methods.

The OAuth 2 spec references the "resource owner" many times throughout the specification. It is the "resource owner" who authorizes access to its data. In many cases, the resource owner is the user who is logging in through the OAuth 2 flow. We took this concept and have provided a convenience mechanism to get information about the resource owner, especially since many OAuth 2 providers return the resource owner ID with the access token (even though this is also not part of OAuth 2).
