### ISSUE TITLE
[Question] Client Credentials Grant with scope

### ISSUE THREAD

**Issue by fmertins** [thephpleague/oauth2-client#774]
Hi folks,

I'm using the package as the "Client Credentials Grant" example from README.md and I'm trying to inform a specific scope called _cbnpagamento_vendas_, appearently without success, example:

```
use League\OAuth2\Client\Provider\GenericProvider;

$options = [
    'clientId' => 'xxx',
    'clientSecret' => 'xxx',
    'urlAuthorize' => 'https://apigw-h.bndes.gov.br/token',
    'urlAccessToken' => 'https://apigw-h.bndes.gov.br/token',
    'urlResourceOwnerDetails' => 'https://apigw-h.bndes.gov.br/cbn-fornecedor',
];

$prov = new GenericProvider($options);
$token = $prov->getAccessToken('client_credentials', ['scope' => ['cbnpagamento_vendas']]);
var_dump($token);
```

And I get:

```
class League\OAuth2\Client\Token\AccessToken#32 (5) {
  protected $accessToken =>
  string(36) "7b27b500-89a2-36b8-8f9c-xxx"
  protected $expires =>
  int(1551893968)
  protected $refreshToken =>
  NULL
  protected $resourceOwnerId =>
  NULL
  protected $values =>
  array(2) {
    'scope' =>
    string(28) "am_application_scope default"       <== HERE!
    'token_type' =>
    string(6) "Bearer"
  }
}
```

If I request the token without specifing the second parameter `['scope' => ['cbnpagamento_vendas']]` I get the same result (same scopes "am_application_scope default"), so it seems to me that parameter doesn't make any difference.

What am I doing wrong?
Thank you!

**Comment by fmertins** [comment]
I've changed my code to inform the scopes key on the $options param when instantiating the provider, but nothing has changed, I still get the same scopes, ie:

```
$options = [
    'clientId' => 'jnKh1MAlfMZHqfpmdzGRrHtIAe0a',
    'clientSecret' => 'wC3rwel0nSjTMNmOfScynRHK7Rka',
    'urlAuthorize' => 'https://apigw-h.bndes.gov.br/token',
    'urlAccessToken' => 'https://apigw-h.bndes.gov.br/token',
    'urlResourceOwnerDetails' => 'https://apigw-h.bndes.gov.br/cbn-fornecedor',
    'scopes' => ['cbnpagamento_vendas'],
];

$provider = new GenericProvider($options);
$token = $provider->getAccessToken('client_credentials');
var_dump($token);
```

```
class League\OAuth2\Client\Token\AccessToken#32 (5) {
  protected $accessToken =>
  string(36) "4455c031-9b5c-3af5-af42-5b60cd74c7c1"
  protected $expires =>
  int(1551898135)
  protected $refreshToken =>
  NULL
  protected $resourceOwnerId =>
  NULL
  protected $values =>
  array(2) {
    'scope' =>
    string(28) "am_application_scope default"
    'token_type' =>
    string(6) "Bearer"
  }
}
```

I wonder, is there any way I could see the built URL, or a log of the request, like cURL...?

**Comment by ramsey** [comment]
It looks like you’re doing everything correctly and the provider is returning the scope string you see. I’m not sure if we expose a way to access the response you receive, but the easiest way might be to set up a proxy like Charles and follow the instructions here to see the requests/responses: https://github.com/thephpleague/oauth2-client/blob/master/README.md#using-a-proxy

**Comment by ramsey** [comment]
If you’re not familiar with Charles, you can get it here: https://www.charlesproxy.com

**Comment by fmertins** [comment]
Hi there, thank you very much I'll try that.

**Comment by ezandonai** [comment]
I tryed to do that to use Uber API, but doesn't work because `getAuthorizationUrl` method calls `getAuthorizationParameters` method that do an implode whit the scope to send in the request.
This:
```
if (is_array($options['scope'])) {
     $separator = $this->getScopeSeparator();
     $options['scope'] = implode($separator, $options['scope']);
}
```
And the `getAccessToken` method doesn't do that because don't expect scopes.
I've only been able to do it right by setting the scope to string. 
And then sending together:
```
$options = [
     'scope' => 'scope_1 scope_2 scope_3'
];
$provider->getAccessToken('client_credentials', $options);
```

**Comment by fmertins** [comment]
Hi folks, I remember I ended up implementing by myself using `curl()` instead of trying to figure out what was happening inside the oauth2-client code. I'll try to review/resume my code, I suspect *maybe* there's a bug here, related to scopes?

**Comment by ezandonai** [comment]
I don't know if it's a bug, but needs an implementation to treat the scope when use it on `getAccessToken` method.

**Comment by bampnet** [comment]
A possible solution is implement the scope on file src/Provider/AbstractProvider.php.
Before:
`public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri
        ];`

After:
`public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri,
            'scope' => $this->getDefaultScopes()
        ];`

**Comment by imclean557** [comment]
@bampnet you should probably check that it's not already set.

```
        if (!isset($options['scope'])) {
          $options['scope'] = $this->getDefaultScopes();
        }
```

**Comment by imclean557** [comment]
Better yet, this formats everything correctly.   `$options = $this->getAuthorizationParameters($options);`

Full method, which should resolve the issue @ezandonai has with needing to set the scope to be a string.

```
    public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri,
        ];

        $options = $this->getAuthorizationParameters($options);
        $params   = $grant->prepareRequestParameters($params, $options);
        $request  = $this->getAccessTokenRequest($params);
        $response = $this->getParsedResponse($request);
        if (false === is_array($response)) {
            throw new UnexpectedValueException(
                'Invalid response received from Authorization Server. Expected JSON.'
            );
        }
        $prepared = $this->prepareAccessTokenResponse($response);
        $token    = $this->createAccessToken($prepared, $grant);

        return $token;
    }

```

**Comment by ramsey** [comment]
All providers are different, and the `GenericProvider` may not work for all of them. It works for many cases, but not every provider follows the OAuth 2 spec. This is why we made league/oauth2-client extensible, so you can extend `AbstractProvider` to modify things according to the needs of the provider you're trying to use.

@ezandonai, you should check out [stevenmaguire/oauth2-uber](https://github.com/stevenmaguire/oauth2-uber). It's a custom provider for Uber that handles the issues you described with the scope.

@imclean557, if `scopes` is passed in through the `$options` parameter, there's no need to also call `$this->getAuthorizationParameters($options)`. This will have the result of adding additional query string parameters to the request that should only used for the authorization request. When the `$options` are prepared and sent to `getAccessTokenRequest()`, they are already added to the query string (if it is a `GET` request).

The issue @fmertins reported originally is that the scope `am_application_scope default` was set on the `AccessToken` object no matter what scopes he provided when calling `getAccessToken()`. The only way league/oauth2-client could do this is by setting the value we received from the OAuth 2 server. I don't believe there is a bug in the oauth2-client code that caused this. I think the problem was on the server's side. Perhaps it always sets `am_application_scope default`, if it receives no scope or a scope it doesn't understand, so perhaps it didn't understand `cbnpagamento_vendas`, or maybe this was misspelled.

These are just guesses, but I don't believe @fmertins's issue is related to the issue @ezandonai encountered with the Uber OAuth 2 provider or the problem that @imclean557 is trying to solve. Maybe I'm wrong?

I'll close this issue for now. If it is still a problem, please open a new issue, and we'll try to get more details.

**Comment by imclean557** [comment]
Thanks for the information @ramsey. I'll need to look into it again more carefully, but from memory the problem was there was no way to pass the scope to `getAccessToken()` using HttpBasicAuthOptionProvider and client credentials grant.  Our server requires a scope when using basic auth.

**Comment by ramsey** [comment]
@imclean557 I believe the `$params` passed to `OptionProviderInterface::getAccessTokenOptions()` has the `scope` in it, so you should be able to create your own option provider that implements `OptionProviderInterface` and call `setOptionProvider()` on the provider object to set it. You could probably achieve what you need by extending `HttpBasicAuthOptionProvider` and overriding `getAccessTokenOptions()`, adding the `scope` to the headers, as needed.

**Comment by imclean557** [comment]
@ramsey,

> You could probably achieve what you need by extending HttpBasicAuthOptionProvider and overriding getAccessTokenOptions(), adding the scope to the headers, as needed.

This looks like the solution in this case. I was trying to use the oauth2-client as "off the shelf" as possible but extending one class shouldn't be a problem.  Thanks.

**Comment by ramsey** [comment]
While we provide the `GenericProvider` for convenience, oauth2-client isn't really intended to be used "off the shelf." Everyone's OAuth implementation is just a little different, as you've found. 😉
