### ISSUE TITLE
Access Token is not generating 

### ISSUE THREAD

**Issue by Surendaran-Cg** [thephpleague/oauth2-client#776]
$accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);

Throws Invalid client error.

**Comment by chaicai333** [comment]
i having the same issue

**Comment by tttttony** [comment]
Which version of PHP are you running, I had to upgrade to PHP 7+, the state is generated using 

```
    protected function getRandomState($length = 32)
    {
        // Converting bytes to hex will always double length. Hence, we can reduce
        // the amount of bytes by half to produce the correct length.
        return bin2hex(random_bytes($length / 2));
    }
```
Which requires PHP 7+ for `random_bytes`, if you override this method in your provider, you should be able to bypass this issue.

**Comment by ramsey** [comment]
@tttttony, since we use paragonie/random_compat as a polyfill for `random_bytes()` on PHP 5.6, upgrading to PHP 7 is not a requirement.

"invalid client" is an error that comes back from the OAuth server, so you'll need to check the provider's documentation to find out why you're getting this error. It is usually due to having incorrect `clientId` or `clientSecret`.
