### ISSUE TITLE
Refreshing token does not throw error when server returns 401

### ISSUE THREAD

**Issue by shuki25** [thephpleague/oauth2-client#785]
I'm attempting to write try and catch blocks for error handling when refreshing access token.  When the OAuth2 server responded with a 401 error code (invalid refresh token), the script threw a unexpected exception.  Debug log shows:

```
[2019-05-13 12:10:29] console.ERROR: Error thrown while running command "app:capi-refresh-token". Message: "Required option not passed: "access_token"" {"exception":"[object] (InvalidArgumentException(code: 0): Required option not passed: \"access_token\" at /var/projects/sites/edscc/vendor/league/oauth2-client/src/Token/AccessToken.php:62)","command":"app:capi-refresh-token","message":"Required option not passed: \"access_token\""} []
```

Here's the code snippet:

```
$grant = new RefreshToken();
                try {
                    $newAccessToken = $this->OAuth2Helper->getAccessToken($grant, [
                        'refresh_token' => $oauth2->getRefreshToken(),
                        'type' => 'refresh'
                    ]);
                    $this->OAuth2Helper->saveAccessTokenToDataStore($item->getUser(), $newAccessToken);
                    $count++;
                }
                catch (IdentityProviderException $e) {
                    $this->errorLogHelper->addErrorMsgToErrorLog('CapiRefreshAuth', $e->getCode(), $e);
                    $oauth2 = $item->getUser()->getOauth2();
                    $oauth2->setRefreshFailed(true);
                    $failed++;
                }
```
The script stops at `$this->OAuth2Helper->getAccessToken()` and does not go any further. I don't understand why my try/catch block didn't capture the exception but instead your library threw an error and stopped there.  Is there a way I can handle this gracefully?

TIA,
Josh

**Comment by ramsey** [comment]
Your try/catch isn't catching it because the exception is `InvalidArgumentException` and not `IdentityProviderException`.

It looks like this is because we always require the `access_token` parameter:

https://github.com/thephpleague/oauth2-client/blob/badb01e62383430706433191b82506b6df24ad98/src/Token/AccessToken.php#L86-L99

If you add `access_token` to the array you're passing to `getAccessToken()`, then it should work.

[RFC 6749, section 6](https://tools.ietf.org/html/rfc6749#section-6) doesn't list `access_token` as a required parameter for refreshing a token, but I think we required it in the base oauth2-client library because, at the time, most providers required it. If you do not want to pass it, you could implement a custom provider with a custom access token object.

If you choose to create a custom provider, start here: https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDER-GUIDE.md
