### ISSUE TITLE
form_params not working

### ISSUE THREAD

**Issue by thewebsitedev** [thephpleague/oauth2-client#803]
Hi there,

Thank you for this library!

I am trying to make a post request where I need to send a couple of parameters as well. But the parameters are not being included with the request.

Working CURL request:
```
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'aid=...&api_token=...&user_token=...' 'https://mywebsite.com/api/subscription/list'
```

Not Working Request:
```
$request = $provider->getAuthenticatedRequest(
    'POST',
    'https://mywebsite.com/api/subscription/list',
    $existingAccessToken->getToken(),
    [
        'form_params' => [
            'aid'        => '...',
            'api_token'  => '...',
            'user_token' => $existingAccessToken->getToken()
        ]
    ]
);
```

Error Message:
```
array(4) {
  ["code"]=>
  int(400)
  ["ts"]=>
  int(1569391222)
  ["validation_errors"]=>
  array(1) {
    ["message"]=>
    string(19) "aid cannot be empty"
  }
  ["message"]=>
  string(30) "Validation errors, see details"
}
```

What did I miss?

**Comment by Bibendus83** [comment]
I have the same issue, form_params is completely ignored!

**Comment by Bibendus83** [comment]
Ok, I finally found a solution.
This library doesn't support the `form_params` option but only `headers`, `body` and `version` as you can see here:
https://github.com/thephpleague/oauth2-client/blob/a68854ffbfa3e301264c287a1f27f3f6404ea246/src/Tool/RequestFactory.php#L75-L86

The only solution is to work manually with the `body` option, here is what I have done (and posted on StackOverflow 
https://stackoverflow.com/questions/52718933/making-post-request-with-thephpleague-oauth2-client/60674068#60674068)
```
$postData = [
    'date' => $date,
    'service_ids' => $serviceId,
];
$options = [
    'body' => http_build_query($postData),
    'headers' => [
        'Content-Type' => 'application/x-www-form-urlencoded',
    ],
];

$request = $this->provider->getAuthenticatedRequest("POST", $requestUrl, $token, $options);
$response = $this->provider->getParsedResponse($request);
```

Some said that it should work using `json_encode()` instead of `http_build_query()` and `application/json` in the Content-Type but I was not able to make it work that way.
I posted this answer on StackOverflow too

**Comment by dpi** [comment]
Created #863 to expand on this

**Comment by ramsey** [comment]
Closing since there is a work-around. We'll treat #863 as a feature request. Thanks!
