### ISSUE TITLE
Requesting multiple scopes causes failure

### ISSUE THREAD

**Issue by Rudigern** [thephpleague/oauth2-client#834]
When requesting multiple scopes, it looks like the OAuth2 standard delimits them via `space` however when doing it via the recommended way it delimits it via `,`. eg:

`$authorizationUrl = $provider->getAuthorizationUrl(array("scope" => array('one', 'two')));`

delimits it via `,`. Changing it to:

`$authorizationUrl = $provider->getAuthorizationUrl(array("scope" => 'one two'));`

fixes it. It's easy worked around however if we're abiding by the spec shouldn't the array be delimited by `space`?

**Comment by ramsey** [comment]
Looks like you're correct:

> The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings.  The strings are defined by the authorization server.  If the value contains multiple space-delimited strings, their order does not matter, and each string adds an additional access range to the requested scope.

— From https://tools.ietf.org/html/rfc6749#section-3.3

I believe we opted to use a comma because many OAuth2 providers originally used commas, instead of following the spec. However, we do make this easy to change.

You may extend `AbstractProvider` and override `getScopeSeparator()`, returning an single space character, rather than a comma: https://github.com/thephpleague/oauth2-client/blob/3bf4897fccdeedbf189513059854a22319b261e3/src/Provider/AbstractProvider.php#L318-L327

**Comment by shunkica** [comment]
Why was this not changed to space? The default implementation doesn't work with the `league/oauth2-server` which expects a space delimited scope list.
