### ISSUE TITLE
AccessToken expires is strange

### ISSUE THREAD

**Issue by JuergvonBueren** [thephpleague/oauth2-client#860]
When I get an Acces Token (Azure OAuth2) and run
$accessToken->getExpires()
I get a value of 1602845222
Documented is a lifetime of 1 hour, resp. 3599 (seconds) are returned.
In Your Implementation I see that You make a guess if the return is a lifetime in seconds or a expiration timestamp.
Anyway You try to return a expiration timestamp.
So when I do 
echo 'Expires: '. date('Y-m-d H:i:s', $expires) ; // $expires is $accessToken->getExpires()
I get 
Expires: 1970-01-01 01:00:00
Not really helpful.
So is it really a good idea to make this guess?
In my case I would have to add time() to the result and to get the "lifetime" I would have to calculate a timeDiff....

My suggestion would be...
return in getExpires() what You get and have an additional function like expiresAt() with the guessed Timesatmp.

**Comment by ramsey** [comment]
RFC 6749 defines the parameter as `expires_in`, but some providers use the nonstandard `expires`.

The `expires_in` parameter is always understood to be the seconds (from now) until the access token expires.

Since there isn't a provider that handles this 100% according to the specification, we've chosen to convert all expires values to the Unix Epoch (seconds since midnight UTC on 1 January 1970).

If we get `expires_in`, we assume the provider is following the spec, so we add the current Unix timestamp to the `expires_in` time. So, if the current Unix timestamp is `1603853087` (2020-10-28 02:44:47) and `expires_in` is `1209600` (14 days from now), then we add `1603853087 + 1209600` to get `1605062687` (2020-11-11 02:44:47).

This is the value returned when you call `getExpires()`.

However, if the provider returns `expires`, we don't know if they mean "expires in this many seconds from now" or "expires at this timestamp," so we have to make an educated guess. We do this by [checking to see if the value is greater than the date of the OAuth 2 draft](https://github.com/thephpleague/oauth2-client/blob/badb01e62383430706433191b82506b6df24ad98/src/Token/AccessToken.php#L142-L154). If it is, then we assume the value is a timestamp, and we treat it as the expires time.

If the value is less than the date of the OAuth 2 draft, we assume it means "expires in this many seconds from now," so we add the value to the current timestamp, like we do with `expires_in`.

See here: https://github.com/thephpleague/oauth2-client/blob/badb01e62383430706433191b82506b6df24ad98/src/Token/AccessToken.php#L109-L128

I hope this helps.

**Comment by JuergvonBueren** [comment]
Hello Ben,
Thank You very much for this explanation. Now I understand.
I'll close this "Issue".
BR Jürg
